import Head from 'next/head'
import styled from 'styled-components'
import { useUserAgent } from '@/contexts/userAgent/useUserAgent'
import { PcScreen } from '@/components/pc/screen'
import { SpScreen } from '@/components/sp/screen'

type Props = {
  className?: string
}

const Component = ({ className }: Props): JSX.Element => {
  const userDevice = useUserAgent()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={className}>
        {userDevice.isMobile ? (
          <div suppressHydrationWarning>
            <SpScreen />
          </div>
        ) : (
          <div suppressHydrationWarning>
            <PcScreen />
          </div>
        )}
      </main>

      <footer>
      </footer>
    </div>
  )
}

const StyledComponent = styled(Component)`
`

export default function Home() {
  return <StyledComponent />
}
