import Head from 'next/head'
import styled from 'styled-components'

type Props = {
  className?: string
}

const Component = ({ className }: Props): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={className}>
        <h1 className="title">
          Welcome to Next.js!
        </h1>
      </main>

      <footer>
      </footer>
    </div>
  )
}

const StyledComponent = styled(Component)`
  padding: 150px;

  > .title {
    font-size: 50px;
  }
`

export default function Home() {
  return <StyledComponent />
}
